import type { Metadata } from "next";
import "./globals.css";
import MyHeader from "./components/MyHeader/MyHeader";
import robotoCondensed from "./fonts/font";


export const metadata: Metadata = {
  title: "Planets",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={robotoCondensed.className}>
        <MyHeader />
        {children}
      </body>
    </html>
  );
}


